from __future__ import annotations

from typing import Protocol


class SettingsAdapter(Protocol):
    def is_chatgpt_available(self) -> bool: ...

    def open_personalization(self) -> None: ...

    def read_custom_instructions(self) -> str | None: ...

    def write_custom_instructions(self, value: str) -> None: ...
